### ISSUE TITLE
more general zigbee support

### ISSUE THREAD

**Issue by mrose17** [exsilium/homebridge-xbee#1]
hi @exsilium! have you given any thought as to what it would take to use an digi product to provide a homebridge-zigbee plugin? i'm wondering whether i could use an xbee gateway or xstick to do the "zigbee stuff" and have the plugin know about different kinds of HA devices and provide the homekit layer.

any experience with either of those products? thanks!

**Comment by exsilium** [comment]
Hi @mrose17! I think it all boils down to what you'd expect the homebridge-zigbee plugin to do? If your intent is to join an existing ZigBee network and just issue specific commands to end devices, that should be simple enough and you could use homebridge-xbee to accomplish that. In fact, if you check the currently hardcoded Trigger signal, it uses the same clusterID as specified in ZigBee HA as On/Off cluster.

If you want your future plugin to "know" the devices running in the network, you'd need to implement device and capability discovery as defined in the [ZigBee Cluster Library Specification][zcl] and [ZigBee Home Automation Profile][zha].

Personally, I haven't gone beyond controlling XBee radios and programmable XBee radios running custom profile and commands as I don't own any off-the-shelf ZigBee devices myself so I don't have a running network I could easily use to experiment the discovery part. Having said that, if you can use your XStick to join your ZigBee network so you can send some frames, then nothing stops you from using homebridge plugin to talk with the rest of the network. Either doing proper discovery or just hardcoding the devices you have in your network.

If you are looking more into the information how your device can join a ZB network. Digi has a [KB article][digi] about the debugging part.

Cheers! 🍻 

[zcl]: http://www.zigbee.org/non-menu-pages/zigbee-cluster-library-specification-download/
[zha]: http://www.zigbee.org/zigbee-for-developers/applicationstandards/zigbeehomeautomation/
[digi]: http://knowledge.digi.com/articles/Knowledge_Base_Article/Debugging-joining-in-a-XBee-ZigBee-ZB-network-using-the-AI-command

**Comment by mrose17** [comment]
thanks for the reply!

initially, i should probably start with something small. i have a number of Quirky Trippers that are zigbee-enabled reed sensors. for those, there's only a couple of properties: contact on/off, tamper on/off, and battery level.

i imagine that going the xstick route is best, though i am sort of hoping there's a REST API on the xbee gateway ... either way, i'd be writing some code, i'm just thinking there's probably less code to write (and easier code to debug) doing REST...

many thanks!

cheers!

**Comment by exsilium** [comment]
Thanks for sharing! Not sure if you're aware but SmartThings has support for them. It helps in understanding how the [init and triggers](https://github.com/mitchpond/SmartThingsPublic/blob/master/devicetypes/mitchpond/quirky-wink-tripper.src/quirky-wink-tripper.groovy) are done.

**Comment by mrose17** [comment]
hi again! i still have my wink hub (in fact i have two... i used to work at wink!) and it works great, i'm just trying to see if i can get everything consolidated under one system. i've asked the folks at digi if they can give me some pointers. i think it would be good to have a "generic" zigbee platform for homebridge, so perhaps something will happen here!

best,

/mtr
